const { h } = require('haipa');
const { fonts } = require('../meta');
require('./haipaExt');

module.exports = class Template {
	build = (data) => h().html(h()
		.lang('en')
		.head(h()
			.title(h().txt(`${data.title ? `${data.title} - ` : ''}mattia.id`))
			.meta(h().name('Description').content(data.desc))
			.encoding()
			.viewport()
			.stylesheet('/media/style.css')
			.allFonts(fonts)
		)
		.body(h().class('checkerboard')
			.main(h().class(data.accent)
				.header(h()
					.section(h().id('tiltedTop')
						.div(h().id('topText').class('bigShadow')
							.a(h().href('/').id('homeLink').class('hoverFloat').alt('Home')
								.h1(h().txt('Mattia Schiano'))
							)
							.aside(h().id('socialLinks')
								.socialIcon('github', 'https://github.com/matteron')
								// Disabling while I try to find a job.  You know how companies are.
								// .socialIcon('twitter', 'https://twitter.com/mattiaschiano_')
							)
						)
						.svg(h().id('headerLine').version('1.1').viewBox('0 0 525 4').xmlns('http://www.w3.org/2000/svg')
							.g(h().fill('none').fillRule('evenodd').strokeDasharray('12').strokeLinecap('round').strokeOpacity('.35')
								.g(h().transform('translate(-235, -369)').stroke('#222').strokeWidth('4').id('headerLineColor')
									.g(h().transform('translate(237 320)')
										.path(h().d('m0 51h550'))
									)
								)
							)
						)
					)
					.nav(h().navList(data.title))
				)
				.article(h()
					.class(`smallShadow ${data.title === 'projects' ? 'markdown' : ''}`)
					.id(data.title === 'projects' ? 'projectList' : '')
					.txt(data.body)
				)
			)
		)
	).render();
}