// const { tags, attr } = require('haipa');
// const { allFonts, allCss, allProjects } = require('./haipaExt');
const { h } = require('haipa');
const Tag = require('./haipaExt');

exports.base = (p) => h().html(h()
	.lang('en')
	.head(h()
		.title(h().txt(`${p.title ? `${p.title} - ` : ''}mattia.id`))
		.meta(h().name('Description').content(p.desc))
		.encoding()
		.viewport()
		.stylesheet(p.css)
		.allFonts(p.fonts)
	)
	.body(h().class('checkerboard')
		.main(h().class(p.accent)
			.header(h()
				.section(h().id('tiltedTop')
					.div(h().id('topText').class('bigShadow')
						.a(h().href('/').id('homeLink').class('hoverFloat').alt('Home')
							.h1(h().txt('Mattia Schiano'))
						)
						.aside(h().id('socialLinks')
							.socialIcon('github', 'https://github.com/matteron')
							.socialIcon('twitter', 'https://twitter.com/mattiaschiano_')
						)
					)
					.svg(h().id('headerLine').version('1.1').viewBox('0 0 525 4').xmlns('http://www.w3.org/2000/svg')
						.g(h().fill('none').fillRule('evenodd').strokeDasharray('12').strokeLinecap('round').strokeOpacity('.35')
							.g(h().transform('translate(-235, -369)').stroke('#222').strokeWidth('4').id('headerLineColor')
								.g(h().transform('translate(237 320)')
									.path(h().d('m0 51h550'))
								)
							)
						)
					)
				)
				.nav(h().navList(p.title))
			)
			.article(h()
				.class(`smallShadow ${p.title == 'projects' ? 'markdown' : ''}`)
				.id(p.title === 'projects' ? 'projectList' : '')
				.txt(p.body)
			)
		)
	)
).render();

exports.projectList = (pList) => h().div(h()
	.h2(h().txt('little of this and that'))
	.allProjects(pList)
).render();